---
# - name: Create cluster entries in /etc/hosts for all nodes
#   lineinfile:
#     path: /etc/hosts
#     line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}-c.novalocal {{ item }}-c"
#     regexp: "^.* {{ item }}$"
#     create: no
#     state: present
#   with_items:
#     - "{{ ansible_play_hosts }}"


- name: "Show nodes hostvars"
  debug: var=hostvars

# - fail:
#     msg: "STOP!!!!"



- name: Create entries in /etc/hosts for all nodes
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['secondary_ip'] if ('secondary_ip' in hostvars[item]) else hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}.novalocal {{ item }}"
    regexp: "^.* {{ item }}$"
    create: no
    state: present
  with_items:
    - "{{ ansible_play_hosts }}"

