
- name: Install packages required for docker
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual

- name: Add dockerproject apt key
  apt_key:
    keyserver: ha.pool.sks-keyservers.net
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Add dockerproject apt source
  lineinfile:
    line: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
    dest: /etc/apt/sources.list.d/docker.list
    create: yes
    owner: root
    group: root
    mode: 0644

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install docker engine
  apt:
    name: docker-engine
    state: latest
  notify:
    - Start docker

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    append: yes
    groups: docker
