
# - name: configure rsyslog
#   lineinfile:
#     dest: /etc/rsyslog.conf
#     create: yes
#     state: present
#     line: "{{ item }}"
#     regexp: "^{{item}}"
#   with_items:
#       - $ModLoad imudp
#       - $UDPServerRun 514
#   notify:
#     - restart rsyslog

# - name: rsyslog 50-default.conf
#   lineinfile:
#     dest: /etc/rsyslog.d/50-default.conf
#     create: yes
#     state: present
#     insertbefore: BOF
#     line: "*.*                         @{{ elastic_logstash1 }}:9514;json-template"
#   notify:
#     - restart rsyslog

# - name: rsyslog 01-json-template.conf
#   copy:
#     content: |-
#       template(name="json-template"
#         type="list") {
#           constant(value="{")
#             constant(value="\"@timestamp\":\"")     property(name="timereported" dateFormat="rfc3339")
#             constant(value="\",\"@version\":\"1")
#             constant(value="\",\"message\":\"")     property(name="msg" format="json")
#             constant(value="\",\"sysloghost\":\"")  property(name="hostname")
#             constant(value="\",\"severity\":\"")    property(name="syslogseverity-text")
#             constant(value="\",\"facility\":\"")    property(name="syslogfacility-text")
#             constant(value="\",\"programname\":\"") property(name="programname")
#             constant(value="\",\"procid\":\"")      property(name="procid")
#           constant(value="\"}\n")
#       }
#     force: yes
#     dest: /etc/rsyslog.d/01-json-template.conf
#   notify:
#     - restart rsyslog

# - name: setup journald and syslog
#   lineinfile:
#     dest: /etc/systemd/journald.conf
#     create: yes
#     state: present
#     line: "ForwardToSyslog=yes"
#   notify:
#     - restart journald
