---
- name: Reload systemd
  command: systemctl daemon-reload
  # when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: restart kubelet
  service: name=kubelet state=restarted enabled=yes
  become: true
  
- name: reload systemd
  command: systemctl daemon-reload
  # when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: restart docker
  service:
    name: docker
    state: restarted
