
- name: Install packages required for docker
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
    - aufs-tools

- name: Add dockerproject apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add dockerproject apt source
  lineinfile:
    line: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
    dest: /etc/apt/sources.list.d/docker.list
    create: yes
    owner: root
    group: root
    mode: 0644

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install docker ce
  apt:
    name: docker-ce
    state: latest
  notify:
    - Start docker

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    append: yes
    groups: docker
