
- name: Format docker lib
  filesystem:
    fstype: xfs
    dev: /dev/vdb

- name: mount docker lib
  mount:
    name: /var/lib/docker
    src: /dev/vdb
    opts: defaults,noatime
    dump: 0
    passno: 0
    fstype: xfs
    state: mounted

- name: Ensure the /var/lib/docker directory mountpoint exists
  file:
    path: /var/lib/docker
    state: directory
