
- name: Format docker lib
  filesystem:
    fstype: xfs
    dev: /dev/sdb

- name: Ensure the /var/lib/docker directory mountpoint exists
  file:
    path: /var/lib/docker
    state: directory

- name: mount docker lib
  mount:
    name: /var/lib/docker
    src: /dev/sdb
    opts: defaults,noatime
    dump: 0
    passno: 0
    fstype: xfs
    state: mounted


- name: Format test fs
  filesystem:
    fstype: xfs
    dev: /dev/sdc

- name: Ensure the /var/lib/testfs directory mountpoint exists
  file:
    path: /var/lib/testfs
    state: directory

- name: mount test fs
  mount:
    name: /var/lib/testfs
    src: /dev/sdc
    opts: defaults,noatime
    dump: 0
    passno: 0
    fstype: xfs
    state: mounted
