---

jump_host: hpchard1@ilab-gate.vss.cloud.cam.ac.uk

# This name is used for the Heat stack and as a prefix for the
# cluster node hostnames.
cluster_name: k8s

# This parameter should be set to the name of an RSA keypair you have
# uplaoded to OpenStack.
cluster_keypair: piers-p3

# Site-specific network configuration.
cluster_net:
  - { net: "ilab", subnet: "ilab" }

secondary_net:
  - { net: "p3-bdn", subnet: "p3-bdn" }

# Multi-node application topology.  In this case we have a Dask
# scheduler node (which also offers login services) and a number
# of compute nodes, which mount the same filesystems but are not
# intended to be interactive.
cluster_groups:
  - "{{ k8s_master }}"
  - "{{ k8s_minion }}"

k8s_master:
  name: "controller"
  flavor: "compute-A"
  image: "Ubuntu16"
  num_nodes: 1

k8s_minion:
  name: "compute"
  flavor: "compute-A"
  image: "Ubuntu16"
  num_nodes: 3

# Node group assignments for cluster roles.
# These group assignments are appended to the cluster inventory file.
# The names of these roles are cross-referenced to groups referred to
# in playbooks in the ansible/ directory.
cluster_roles:
  - name: "ceph_client"
    groups: "{{ cluster_groups }}"
  - name: "login"
    groups: [ "{{ k8s_master }}", "{{ k8s_minion }}" ]

cluster_group_vars:
  cluster:
    ansible_user: ubuntu 
    ansible_python_interpreter: python3
