---

- name: "Retrieve project secret from Barbican - secret_name"
  debug: var=secret_name

- name: "Retrieve project secret from Barbican - secret_var"
  debug: var=secret_var


- name: Retrieve project secret from Barbican
  barbi:
    key: "{{ secret_name }}"
  register: barbi_secret

- name: Set fact for the retrieved secret
  set_fact:
    "{{ secret_var }}": "{{ barbi_secret.secret }}"
