---
- name: Load variables
  include_vars:
    file: ../vars/default.yml

- include_tasks: tasks/mount_filesystems.yml

- include_tasks: tasks/dist_upgrade.yml

- include_tasks: tasks/install_docker.yml

- include_tasks: tasks/packages.yml

- include_tasks: tasks/setup_rsyslog.yml
