#!/usr/bin/env ansible-playbook
---

- name: "Apply the common role to shared nodes"
  hosts:
    - k8s_master
    - k8s_minion
  become: yes
  become_method: sudo
  roles:
    - common
  tags:
    - common

- name: "Show debug info"
  hosts:
    - k8s_master
    - k8s_minion
  become: yes
  tasks:
    - name: "Show nodes info"
      debug: var=hostvars[inventory_hostname]
      when: debug

- name: "Setup monitoring services"
  hosts:
    - k8s_master
    - k8s_minion
  become: yes
  roles:
    - monitoring
  tags:
    - monitoring

- name: "Apply the cinder role to the K8s master"
  hosts:
    - k8s_master
  become: yes
  roles:
    - standalone-cinder
  tags:
    - cinder

- name: "Apply the shared role to the K8s nodes"
  hosts:
    - k8s_master
    - k8s_minion
  become: yes
  roles:
    - k8s
  tags:
    - k8s
