---
# private agents - all except first two
agent_list:
- 10.60.253.54

# Use this bootstrap_url value unless you have moved the DC/OS installer assets.
bootstrap_url: http://10.60.253.32:5001
cluster_name: shared_services
exhibitor_storage_backend: static
master_discovery: static
#ip_detect_public_filename: /home/ubuntu/genconf/ip-detect

# one master - first node
master_list:
- 10.60.253.25

# one public agent 2nd node
public_agent_list:
- 10.60.253.20
##- 10.60.253.25
##- 10.60.253.20
##- 10.60.253.54
#
# nameserver 10.60.253.10
# search alaskalocal
resolvers:
- 10.60.253.10

ssh_port: 22
ssh_user: ubuntu
use_proxy: 'false'
#http_proxy: http://<proxy_host>:<http_proxy_port>
#https_proxy: https://<proxy_host>:<https_proxy_port>
#no_proxy: 
#- 'foo.bar.com'
#- '.baz.com'
